### ISSUE TITLE
GraphQLError originalError prop missing on sentry addEventId

### ISSUE THREAD

**Issue by snake575** [graphql-hive/envelop#1394]
Sentry Plugin `addEventId` function builds a `GraphQLError` instance missing the `originalError` prop.

https://github.com/dotansimha/envelop/blob/9449ef36f61d4d9561f88a87204b3a16f3c6f98e/packages/plugins/sentry/src/index.ts#L114-L117

This creates issues when using it togheter with `useMaskedErrors` as the default `formatError` function relies on `originalError` down the line.

https://github.com/dotansimha/envelop/blob/9449ef36f61d4d9561f88a87204b3a16f3c6f98e/packages/core/src/plugins/use-masked-errors.ts#L19-L21

**Comment by n1ru4l** [comment]
@snake575 As I understand correctly here, it seems like `EnvelopErrors` are not filtered out from being processed here: https://github.com/dotansimha/envelop/blob/af4f877ae73d879fd076aa62da4a918f43980d3b/packages/plugins/sentry/src/index.ts#L260-L261

@Jomik As I see it only errors should only be transformed after being checked with the `skipError` function. By default `EnvelopErrors` should be treated as expected errors that don't require any Sentry reporting.

Furthermore, the `.originalError` property should be kept. Instead of re-creating the whole error, it might be a smarter idea to mutate the error extensions instead.

**Comment by lenolib** [comment]
We were just bitten by this bug and spent some hours hunting it down before finding this reported issue. 
Supplying `eventIdKey: null` as an option seems to bypass it for now, in case someone else encounteres this.

**Comment by jycouet** [comment]
I confirm, if I don't set `eventIdKey: null`, I get this log in my console when I have an error:

```bash
ERR TypeError: Cannot set properties of undefined (setting 'sentryEventId')
    at addEventId (file:///home/jycouet/prj/node_modules/.pnpm/@envelop+sentry@5.1.1_v4ebpnkvuk656xuwvqsgwe2dx4/node_modules/@envelop/sentry/esm/index.js:21:40)
    at file:///home/jycouet/prj/node_modules/.pnpm/@envelop+sentry@5.1.1_v4ebpnkvuk656xuwvqsgwe2dx4/node_modules/@envelop/sentry/esm/index.js:136:44
    at Array.map (<anonymous>)
    at file:///home/jycouet/prj/node_modules/.pnpm/@envelop+sentry@5.1.1_v4ebpnkvuk656xuwvqsgwe2dx4/node_modules/@envelop/sentry/esm/index.js:110:63
    at Hub.withScope (/home/jycouet/prj/node_modules/.pnpm/@sentry+core@7.41.0/node_modules/@sentry/core/cjs/hub.js:98:7)
    at Module.withScope (/home/jycouet/prj/node_modules/.pnpm/@sentry+core@7.41.0/node_modules/@sentry/core/cjs/exports.js:143:23)
    at handleResult (file:///home/jycouet/prj/node_modules/.pnpm/@envelop+sentry@5.1.1_v4ebpnkvuk656xuwvqsgwe2dx4/node_modules/@envelop/sentry/esm/index.js:98:36)
    at handleStreamOrSingleExecutionResult (file:///home/jycouet/prj/node_modules/.pnpm/@envelop+core@3.0.6/node_modules/@envelop/core/esm/utils.js:105:5)
    at onExecuteDone (file:///home/jycouet/prj/node_modules/.pnpm/@envelop+sentry@5.1.1_v4ebpnkvuk656xuwvqsgwe2dx4/node_modules/@envelop/sentry/esm/index.js:146:28)
    at file:///home/jycouet/prj/node_modules/.pnpm/@envelop+core@3.0.6/node_modules/@envelop/core/esm/orchestrator.js:381:42
    at async YogaServer.getResultForParams (file:///home/jycouet/prj/node_modules/.pnpm/graphql-yoga@3.7.0_jukviheqyaybdjg76ifj2dsifa/node_modules/graphql-yoga/esm/server.js:285:26)
    at async YogaServer.getResponse (file:///home/jycouet/prj/node_modules/.pnpm/graphql-yoga@3.7.0_jukviheqyaybdjg76ifj2dsifa/node_modules/graphql-yoga/esm/server.js:357:23)
    at async YogaServer.handle [as handleRequest] (file:///home/jycouet/prj/node_modules/.pnpm/graphql-yoga@3.7.0_jukviheqyaybdjg76ifj2dsifa/node_modules/graphql-yoga/esm/server.js:38:34)
    at async handleCustom (/src/hooks/handleCustom.ts:7:20)
    at async handleRouteGuard (/src/hooks/handleRouteGuard.ts:14:20)
    at async handleAuth (/src/hooks/handleAuth.ts:24:20)
    at async Module.respond (/@fs/home/jycouet/prj/node_modules/.pnpm/@sveltejs+kit@1.10.0_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/runtime/server/respond.js:248:20)
    at async file:///home/jycouet/prj/node_modules/.pnpm/@sveltejs+kit@1.10.0_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:500:22
```

thx for the tips @lenolib

**Comment by RIP21** [comment]
Have the same error for me too. What's the work around for it?

**Comment by RIP21** [comment]
Got it, passing `eventIdKey: null` into the config of the `useSentry` envelop plugin :)

Wondering why it's still not fixed tho after so much time.

**Comment by RIP21** [comment]
https://github.com/n1ru4l/envelop/blob/main/packages/plugins/sentry/src/index.ts#L102-L105

I assume an error happening there? It assumes that `extensions[eventdKey]` will be there to be set, but it seems that it's not the case. And it needs to first make sure `extensions` are there before setting it. Isn't it? Also, it assumes that the error type will be `GraphQLError` too which is not the guarantee isn't it? 

Maybe it's and I'm wrong, as probably all errors thrown by the resolver layer probably should be wrapped in `GraphQLError` with an `originalError` being set. But is it really a guarantee it will have an `extensions` set? 

I'm using `pothos` as my schema definition/executable schema builder BTW, for reference.

**Comment by Jomik** [comment]
Yeah, probably because `extensions` isn't set.
Seems like this code should change as well.
https://github.com/n1ru4l/envelop/blob/f9e791e50095e933c2f61d080ef2e7a739d17edb/packages/plugins/sentry/src/index.ts#L100
Should probably be this, to follow the logic of the docs.
```ts
const eventIdKey = options.eventIdKey === null ? null : (options.eventIdKey ?? 'sentryEventId');
```
And then we need to initialise `extensions`, if it isn't there.

I am no longer using this at work as I moved to a different team, so I will not be fixing this.
But it seems like a simple fix that you can open a PR for.
@RIP21 seems like you basically already found the cause and solution 😄
