### ISSUE TITLE
Cannot read properties of undefined (reading 'hrtime')

### ISSUE THREAD

**Issue by pablocompagni-contractorvp** [graphql-hive/envelop#1771]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a
     [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) available on
     [Stackblitz](https://stackblitz.com/fork/node).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

I get following error when I include apollo-tracing: `Cannot read properties of undefined (reading 'hrtime')`

Here's the more complete stack trace:

```
TypeError: Cannot read properties of undefined (reading 'hrtime')
    at file:///Users/user/Documents/work/projects/some_project/node_modules/@envelop/apollo-tracing/esm/index.js:31:53
    at field.resolve (file:///Users/user/Documents/work/projects/some_project/node_modules/@envelop/on-resolve/esm/index.js:18:56)
    at resolveField (/Users/user/Documents/work/projects/some_project/node_modules/graphql/execution/execute.js:464:18)
    at executeFields (/Users/user/Documents/work/projects/some_project/node_modules/graphql/execution/execute.js:292:18)
    at executeOperation (/Users/user/Documents/work/projects/some_project/node_modules/graphql/execution/execute.js:236:122)
    at executeImpl (/Users/user/Documents/work/projects/some_project/node_modules/graphql/execution/execute.js:116:14)
    at execute (/Users/user/Documents/work/projects/some_project/node_modules/graphql/execution/execute.js:60:35)
    at graphqlMiddleware (/Users/user/Documents/work/projects/some_project/node_modules/express-graphql/index.js:125:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  locations: [ { line: 4, column: 3 } ],
  path: [ 'deals' ]
}

```
It seems to be failling here, with ctx being undefined for some reason.
<img width="926" alt="image" src="https://github.com/n1ru4l/envelop/assets/82176706/6eddb992-3739-4d5e-973e-04dccc431283">

This is an ESM nodejs project, in case it matters.

**Environment:**

- OS: macOS
- NodeJS: v16/v18
"@envelop/apollo-tracing": "^4.0.6",
 "@envelop/core": "^3.0.6",

**Comment by jdolle** [comment]
I'm encountering this issue for our graphql subscriptions. It seems `onExecute` isnt called when executing a graphql subscription, but the `onResolve` function is still being called for the subscription field.

Also heads up that the link in the codebase for this plugin is not available any longer (https://github.com/apollographql/apollo-server/blob/main/packages/apollo-tracing/src/index.ts)

**Comment by EmrysMyrddin** [comment]
Yes, it seems that this plugin was not made with subscriptions in mind.
Th fix would be to replicate the logic of the `onExecute` hook in the `onSubscribe` hook.
Since subscriptions and simple queries are not using the same executor in `graphql-js`, Envelop offers 2 seperated hooks for the tow kind of operations.
